# Generated by Django 4.2.1 on 2023-10-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_store', '0002_variation'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='product_store.variation'),
        ),
    ]
