# Generated by Django 4.2.1 on 2023-10-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('product_slug', models.CharField(max_length=50, unique=True)),
                ('product_description', models.TextField(blank=True, max_length=512)),
                ('category_image', models.ImageField(blank=True, upload_to='photos/categories')),
            ],
            options={
                'verbose_name': 'Product_category',
                'verbose_name_plural': 'Product_categories',
            },
        ),
    ]
